os: osx
language: objective-c
osx_image: xcode10.1
if: tag =~ ^v

cache:
  directories:
  - vendor/bundle
  - "$HOME/.pub-cache"

before_install:
  - echo $TRAVIS_OS_NAME
  - echo ${HOME}
  - echo ${TRAVIS_BUILD_DIR}
  - gem install cocoapods
  - git clone https://github.com/flutter/flutter.git -b master ${HOME}/flutter
  - cd cruzall
  - ./desktop/setup.sh ../cruzall-desktop
  - export ENABLE_FLUTTER_DESKTOP=true
  - ${HOME}/flutter/bin/flutter doctor -v
  - ${HOME}/flutter/bin/flutter precache --macos
  - ${HOME}/flutter/bin/flutter packages get
  - cd ..

before_script:
  - openssl aes-256-cbc -k $CERTIFICATE_PASSWORD -in fastlane/Certificates/distribution.p12.enc -d -a -out fastlane/Certificates/distribution.p12
  - gem install fastlane

script:
  - fastlane setup_keychain
  - cd cruzall
  - ${HOME}/flutter/bin/flutter -v build macos --release
  - cd ..
  - fastlane developer_id_app

after_success:
  - echo "success"
  - md5 Cruzall.dmg

after_failure:
  - echo "failure"

deploy:
  provider: releases
  api_key:
    secure: hfvmDOwxI61qDz874WwHOaStcO624fme2MJJGUwB1TihAv8RCsG06lMYKLJxAcTeZ3L6fMgjHyV/PJwwF0yowv27BOrEihiyP7oCLQ5VVzQ8nbWuhyTOnvgiH3PuAd+rn5lkjTNJXHufKFw3B+TMRqDa163L1AVYvhH3jzjKc/tcDCgTayeSeFdljXWAQln88mXacQAnzRT0sQRsYf0adqrZiComhG1xkXe4mA1bxdIe+DtPXSLPo+3ah1YfjCW25P7dM3aLVREhm7EM5s+sLwfpgzp5341dsvxoBUGtnOHJH4t8Ab5hZceBZSgLAoJzAc0nggKgBnsUodSusr3GuHwCg9w1jXBXGGi/aI8NlivsiEmJ3fvPlSWxLakCOQJtLTSfWj0/Jlj2PSGLTDCJKeCNH2AvNpppJbtW4PwNw6BOvm0M4112TvcxdRS0gUO6rOP3HycKhPIA6gfvMCG4k7dV5PINX1dstVXVlhFh5Ya8QFAAmhm+dnhCi6Bqqeet2DW5rHLHcPqyLh93Xwby5cFekMkPTNkwB/S+N1IsHMiXLpbsihOodnFCtKKqbF4Jq2eDZdvPhhjB7UjAzLSo2IdSC7SGdLA9gOwn2SNTJ8IPk8yeHWFDHWlkIZ6mfmlIaG6hB2iuIoeJZvdGr2EJZwLO3hEJmx30SZDRwb8yv2E=
  file: Cruzall.dmg
  skip_cleanup: true
  on:
    tags: true
    repo: GreenAppers/cruzall-macos

env:
  global:
  - secure: D3JCLyaeTYvjw4CY6aPRdJVIFlw3OYmmfagYghdjkUuGxgEaXSrDWYtF8cM9lIq5i9TQUHMFEfpRLXnWkAK3hNCi2+G3TQUjRpnwxjMXp0ToCtGDu7lS1/ssECd7anw+UXmLXihohF4gcuzKXKQCCxj4yCEpGM6bS0gwYObMX9Gm5GfJZbRQcOPn3AClSUNQDUHTBRG3r5DuowThNXgrUxv6Jo6OJh3F4Fpjk3GTzraq4Vu3MGEuL8l/Hqcqm0dizeUCvzMzKlS33DiT4ZDlwc8ulKASGDQOwjbyA0pU+FcGNYLj9aV0YP8w3GpzfYSakwYVn2gAudaZZKYwroSYen5KvtyPvUshE77LhH7u4HE40pY66RpOcWDAZKfN0rj0iub4+TzX/LQqEppNMUnu6QzP77UJ5iXuQ+sUo5Y3pQAZBQN4bnyf8IN0zxagePMlson0Dp+eqDAOJPmaUhDrLKyATNBzmSe0YuJge1wGQQh9OSv6rq25Zdeix0bkNjhFstUibF/mjeo3cAY4hRDA7frKeD5z727ONc/DNsdnlFeDi20MUnlySfBHc12O8BRBEtm2sq7w+hDSYpq/bUzaGwx4HXiCSU2D1XxyhL6xLRflpcxsCmlowAvSecCV19TIGbrUsHlBF34C+1kkjtqMNrl/yaHILAIyNmSFtS6qrNg=
  - secure: oc/jpEvUcbUO4yaqDiFX/facUA2Hf5OvKg6Tw3A7HlvHVnXLWcnlVNjeF27Peu5T709oNo8J0CJEntuoAN6AOnVKhDdZc0rqwNU1zYDNaPWOPXA8bbq+2fCTQiJq8GkW54y+97V3xEzcZ/LW1zWBeX9rgWJRcU1cPP10NdosCe3CkYmzHMAUSworQ+5OtvAkC6GMhhekuzHN4IrKpXJ+1VlWNeCdu13Ab9UY1uRCYs+T1w9sYTrI/z7aDFDsB3xOpcgjqKPLyAUhLt8TG42OzROq+3LViLrRQ+EwClmBKYpelbA7jP2l+lctUdDyhCnR9ieneCfLrA2vHP4WN2fouNxKbVMUtih+C9MHVExq/Ws5yTenK6J+UsCIKHMBQZyJB1UX+Ea93pxFPUlYWNKaEu/EioY2aqzfka87dw9yu2Gp9N+RJ5NTr1mRdivZ5+nNLZFzagLFQCfcGgXDIQ+ljJ6Gh9d9JAn/nc3oPgNUQYpND1RO63k151UxT4ZqiBRpyhruFjvzWakqUZz2yedTs5jViMzVrz58tvU6EmwzUVE0ZACdinJc+A299x2JcgnUhqFLQvhkMhlw0ejqKcw/YVeXlmIftmyOqEEaF9iCnLRXShBZEuEyxI7kVvIsKDwAOqcBW3SKj/gQ7hc21xVF/6jSBmaaSOauwlEsaw0VbLc=
